### ISSUE TITLE
Workflow per pass not working correctly.

### ISSUE THREAD

**Issue by moon47usaco** [zamp/comfy-temporal-stability#16]
Would like to be able to specify a different workflow for each pass.

Unless specified the main workflow listed in "Workflow =" will be default

If specified "SwitchWorkflow =" the next renderpass will use the alt workflow.

The idea is to use the ImageEffectsAdjustment node on all EB processed frames to correct the color there rather than as the new frames are generated in comfy.

Currently I use the ImageEffectsAdjustment node to try and match the new processed frames to the slightly less contrast/saturation but that is backwards. What I really want to do is just correct the side affect of EB and process the new frames with normal color values.

I am sure I can come up with other use cases later... =]

IE:
workflow set
comfy pass
eb pass
workflow switch  (workflow with only ImageEffectsAdjustment node)
comfy pass <-- switched workflow to color correct all frames
comfy pass <-- default workflow w/ skip frames
...

**Comment by zamp** [comment]
This is already supported. You can just overwrite the Workflow = parameter per pass. It will default to global value if none is given per pass.

**Comment by moon47usaco** [comment]
Not working for me. repo up to date.

This is what I have in config and the last render still uses the workflow listed at the top. It uses face detailer so its clear its not using the color workflow... 

```
[RenderPass.comfyui]
StartFrame = 2
SkipFrames = 35
comfyuiparam.sampler.denoise = 0.6

[RenderPass.copy_files]
From = ${OutputDir}
To = abc/pass-01/
#----------------------------------------------------------------------p1

[RenderPass.ebsynth_blend]
StartFrame = 2
SkipFrames = 35
Alpha = 0.35

[RenderPass.copy_files]
From = ${OutputDir}
To = abc/eb/pass-02/

Workflow = workflows/color-001_api.json
[RenderPass.comfyui]
```

**Comment by moon47usaco** [comment]
If it works on your end...
Could you show an example how you are able to switch the workflow...??

**Comment by zamp** [comment]
I can't reproduce your issue.

Try adding this into comfyui.py line 91: `print("workflow: " + workflow)` to see if it's reading the correct workflow file.

```python
workflow = config.get("Workflow")
print("workflow: " + workflow) # added line
```

Also double check you've exported the correct api.json

**Comment by moon47usaco** [comment]
It would not let me add the print line, complained about indentation.
Made me realize what was wrong though.

I was setting the workflow before the pass

```
Workflow = workflows/color-001_api.json
[RenderPass.comfyui]
```

It can not get the workflow if it has not started the pass.
Should be :

```
[RenderPass.comfyui]
Workflow = workflows/color-001_api.json
```

User error... =\
